src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("thermoseer.urls", namespace="thermoseer")),
    path("api/", include("demo.urls")),
    path('admin/', admin.site.urls),
]

thermoseer/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'thermoseer'
urlpatterns = [
    path('', views.home, name="home"),
    path('login', views.loginuser, name="loginuser"),
    path('logout', views.logoutuser, name="logoutuser"),
    path('signup', views.signupuser, name="signupuser"),
    path('create/scanner', views.addId, name="add_id"),
    path('create/temperature', views.create_temperature, name="create_temperature"),
    path("thermoser/users", views.users_list, name="users_list"),
    path('thermoser/list', views.temperature_list, name='temperature_list'),
    path('thermoser/details', views.temperature_users_details, name='temperature_users_details'),
    path("thermoser/users/<int:temp_pk>", views.user_scanner_detail, name="user_scanner_detail"),
    path("thermoser/details/<int:temp_pk>", views.temperature_detail, name="temperature_detail"),

]

templates/thermoser/temperature/add-id.html
{% extends "thermoser/base.html" %}
{% load static %}
{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>New ID</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="scanner_id" style="color: #0D0333; font-weight: 900;">ID</label>
                    <input  type="text" name="scanner_id" class="form-control" id="scanner_id" required>
                </div>
                <div class="form-group">
                          <label for="name" style="color: #0D0333; font-weight: 900;">NAME</label>
                    <input  type="text" name="name" class="form-control" id="name" required>
                </div>

                 <div class="form-group">
                          <label for="dept" style="color: #0D0333; font-weight: 900;">DEPARTMENT</label>
                    <input  type="text" name="dept" class="form-control" id="dept" required>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/thermoser/temperature/createtemperature.html

{% extends "thermoser/base.html" %}
{% load static %}
{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>New Temperature</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">Title</label>
                    <input type="text" name="name" class="form-control" id="name" required>
                </div>
                <div class="form-group">
                    <label for="scanner_id">scanner_id</label>
                    <input  type="text" name="scanner_id" class="form-control" id="scanner_id" required>
                </div>
                <div class="form-group">
                          <label for="temp">Temperature</label>
                    <input  type="text" name="temp" class="form-control" id="temp" required>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/thermoser/temperature/detail.html
{% extends "thermoser/base.html" %}

{% block title %}{{ user.name }}{% endblock %}

{% block content %}
    {% if scanner.active %}
          <div class="container bootstrap snippets bootdey">
<div class="row ng-scope" style="margin-top: 20px">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-body text-center">
                <div class="pv-lg"><img class="center-block img-responsive img-circle img-thumbnail thumb96" src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="Contact"></div>
                <h3 class="m0 text-bold">{{ scanner.name }}</h3>
                <div class="mv-lg">
                    <p style="padding:10px 0;">University Of The Cordilleras <br/> {{ scanner.dept }}</p>
                </div>
            </div>
        </div>
        <div class="panel panel-default hidden-xs hidden-sm">
            <div class="panel-heading">
                <div class="panel-title text-center" style="text-align: center; font-weight: 900;">Recent records</div>
            </div>
            <div class="panel-body">
                {% for user_scanner in user_scanners %}
                    {% if user_scanner.active %}
                    <div class="media">
                    <div class="media-left media-middle">
                        <a href="#"><img class="media-object img-circle img-thumbnail thumb48" src="https://bootdey.com/img/Content/avatar/avatar5.png" alt="Contact"></a>
                    </div>
                    <a href="{% url 'thermoseer:user_scanner_detail' user_scanner.scanner_id %}">
                    <div class="media-body pt-sm" style="border-bottom: solid #ababab 2px;">
                        <div class="text-bold" style="margin: 4px;">{{ user_scanner.name }}
                            <div class="text-sm text-muted" style="color: #fabe04!important; margin: 2px 4px;">{{ user_scanner.updated|timesince }} ago</div>
                        </div>
                    </div>
                    </a>
                </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="col-md-8" style="padding: 5px;">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="h4 text-center">Student Information</div>
                <div class="row pv-lg" >
                    <div class="col-lg-2"></div>
                    <div class="col-lg-8">
                        <form class="form-horizontal ng-pristine ng-valid">
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="inputContact1">Name</label>
                                <div class="col-sm-10">
                                    <input class="form-control" id="inputContact1" type="text" value="{{  scanner.name }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="inputContact2">Department</label>
                                <div class="col-sm-10">
                                    <input class="form-control" id="inputContact2" type="email" value="{{ scanner.dept  }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-4 control-label" for="inputContact3" >Student Id</label>
                                <div class="col-sm-10">
                                    <input class="form-control" id="inputContact3" type="text" value="{{  scanner.scanner_id }}">
                                </div>
                            </div>
                            {% if latest_test.temp  %}
                                   <div class="form-group">
                                <label style="color: #fabe04; font-weight: 900;" class="col-sm-9 control-label" for="inputContact4" >Latest Temperature Result</label>
                                <div class="col-sm-10">
                                    <input style="color: #571405; font-weight: 900;" class="form-control" id="inputContact4" type="text" value="{{ latest_test.temp }}">
                                </div>
                            </div>
                                {% else %}
                                   <div class="form-group">
                                <label class="col-sm-9 control-label" for="inputContact4">Latest Temperature Result</label>
                                <div class="col-sm-10">
                                    <input class="form-control" id="inputContact4" type="text" value="0.0">
                                </div>
                            </div>
                            {% endif %}

                        </form>

                    </div>
                </div>
            </div>

        </div>
        {% if temperatures  %}
            <table class="table table-striped table-bordered" style="width:100%">
                    <thead style="color: #ffffff; border: none;">
                    <tr style="text-align: center;">
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Temperature</th>
                         <th scope="col">Status</th>
                        <th scope="col">Time</th>
                    </tr>
                    </thead>
                    <tbody style="text-align: center;">
                    {% for temperature in temperatures %}
                        <tr {% if temperature.status == 'HIGH' %}style="background: #b24c00; border: none;" {% endif %}>
                                <th scope="row">{{ temperature.scanner_id }}</th>
                                <td>{{ temperature.scanner }} </td>
                                <td>{{ temperature.temp }}</td>
                                <td>{{ temperature.status }}</td>
                                <td>{{ temperature.publish|time }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% if temperatures %}{% include "thermoser/pagination.html" with page=temperatures %} {% endif %}

        {% endif %}
    </div>
</div>
</div>
        {% else %}
        <div>
        <h1 style="margin: 20px 0; text-align: center;">No active user</h1>
        </div>
    {% endif %}

{% endblock %}

templates/thermoser/temperature/list.html
{% extends "thermoser/base.html" %}
{% load static %}
{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-10">
            {% if temperatures %}
                <h2 style="text-align: center;">{{ temperatures.count }} List Of Temperature{{ temperatures.count|pluralize }}</h2>
                          <hr class="bannerLine" />
            {% endif %}
        </div>
    </div>
    <div id="showerror">
    <p>[[detail.message]]</p>
    </div>
    <div class="row justify-content-center mt-5">
   {% if temperatures %} %}
     <form action="{% url 'thermoseer:temperature_list' %}" method="GET" class="form-group">
        <label>
            <input style="width: 150%; align-items: center; margin-left: -20%; padding: 20px;"
              type="search"
              name="searchText"
                   id="searchText"
              placeholder="Search name , id , status ..."
              class="form-control"
            />
        </label>
    </form>
   {% endif %}
        <div class="col-md-10">
            {% if temperatures %}
                <div class="list-temperature">
                <table class="table table-striped table-bordered" style="width:100%">
                    <thead>
                    <tr style="text-align: center;">
                        <th style="font-weight: 900; color: #0D0333;" scope="col">ID</th>
                        <th style="font-weight: 900; color: #0D0333;" scope="col">NAME</th>
                        <th style="font-weight: 900; color: #0D0333;" scope="col">TEMPERATURE</th>
                        <th style="font-weight: 900; color: #0D0333;" scope="col">STATUS</th>
                        <th style="font-weight: 900; color: #0D0333;" scope="col">TIME</th>
                        <th style="font-weight: 900; color: #0D0333;" scope="col">DATE</th>

                    </tr>
                    </thead>
                    <tbody style="text-align: center;">
                    {% for temperature in temperatures %}

                        <tr {% if temperature.status == 'HIGH' %}style="background: #b24c00; border: none;" {% endif %}>
                                {% if temperature.scanner_id %}
                                    <th scope="row"> <a href="{% url 'thermoseer:user_scanner_detail' temperature.scanner_id %}">{{ temperature.scanner_id }} </a></th>
                                    <td><a href="{% url 'thermoseer:user_scanner_detail' temperature.scanner_id %}">{{ temperature.scanner }} </a></td>
                                    <td><a href="{% url 'thermoseer:user_scanner_detail' temperature.scanner_id %}">{{ temperature.temp }} </a></td>
                                    <td><a href="{% url 'thermoseer:user_scanner_detail' temperature.scanner_id %}">{{ temperature.status }} </a></td>
                                    <td><a href="{% url 'thermoseer:user_scanner_detail' temperature.scanner_id %}">{{ temperature.publish|time }} </a></td>
                                    <td><a href="{% url 'thermoseer:user_scanner_detail' temperature.scanner_id %}">{{ temperature.publish|date }} </a></td>
                                 {% endif %}
                        </tr>

                    {% endfor %}
                    </tbody>
                </table>
                </div>
                {% include "thermoser/pagination.html" with page=temperatures %}
            {% else %}
                <div class="text-center">
                    <h2>Looks like you don't have any temperature record!</h2>
                    <br>
{#                    <a role="button" class="btn btn-primary" href="{% url 'thermoseer:create_temperature' %}">New#}
{#                        Temperature</a>#}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block domready %}
        vueApp = new Vue({
        el: "#showerror",
        delimiters: ["[[", "]]"],
        data() {
            return {
                detail: {},
            };
        },

    methods: {
        currentDate() {
        const current = new Date();
        return `${current.getHours()}:${current.getMinutes() + 1}:${current.getSeconds()}`;
    }
  }
});
    const ws = new WebSocket("ws://localhost:8000/message/error/")
    ws.onopen = function () {
        ws.send(JSON.stringify({
            action: "retrieve",
            request_id: new Date().getTime(),
        }))
    }
    ws.onmessage = function (e) {
        const allData = JSON.parse(e.data);
        if (allData.action === "retrieve") {
            vueApp.$data.detail = allData.data;
            vueApp.$forceUpdate();
        }else if (allData.action === "create") {
            vueApp.$data.detail = allData.data;
            console.log(allData.data);
             setTimeout(function() {
                    vueApp.$forceUpdate();
                    $("#showerror").css("display","none");
                },
                3000);
            $("#showerror").css("display","block");
        }
    }

    console.log("hello");
{% endblock %}

templates/thermoser/temperature/message-error.html
{% load static %}
{% block content %}
    <div class="card" id="contentdisplay">
        <div class="banner">
            <svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="256"
                 height="256" viewBox="0 0 256 256" xml:space="preserve">
                <g style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; fill-rule: nonzero; opacity: 1;"
                   transform="translate(1.4065934065934016 1.4065934065934016) scale(2.81 2.81)">
	        <path d="M 45 40.05 c -9.34 0 -16.939 -7.599 -16.939 -16.939 v -6.171 C 28.061 7.599 35.66 0 45 0 c 9.341 0 16.939 7.599 16.939 16.939 v 6.171 C 61.939 32.451 54.341 40.05 45 40.05 z"
                style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(55,188,140); fill-rule: nonzero; opacity: 1;"
            transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round"></path>
                    <path d="M 69.139 90 H 20.862 c -4.143 0 -7.513 -3.37 -7.513 -7.513 V 67.927 c 0 -11.157 5.701 -21.278 15.25 -27.074 c 0.745 -0.451 1.694 -0.37 2.35 0.2 c 3.91 3.398 8.9 5.27 14.052 5.27 c 5.151 0 10.142 -1.872 14.053 -5.27 c 0.657 -0.57 1.606 -0.65 2.35 -0.2 C 70.95 46.648 76.65 56.77 76.65 67.927 v 14.561 C 76.65 86.63 73.28 90 69.139 90 z"
                          style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(55,188,140); fill-rule: nonzero; opacity: 1;"
                          transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round"></path></g></svg>
        </div>
    <div id="errormessage">
       <h1 style="color: red;">ERROR MESSAGE</h1>
    </div>
    </div>
{% endblock %}

templates/thermoser/temperature/temperature-dashboard.html

{% extends "thermoser/base.html" %}
{% load static %}
{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>New Temperature</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="scanner">scanner_id</label>
                    <input  type="text" name="scanner" class="form-control" id="scanner" required>
                </div>
                <div class="form-group">
                          <label for="temp">Temperature</label>
                    <input  type="text" name="temp" class="form-control" id="temp" required>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/thermoser/temperature/temperatureDashboard.html
{% extends 'thermoser/base.html' %}
{% load static %}

{% block title %} {% endblock %}

{% block content %}

    <h1>H</h1>
{% endblock %}

templates/thermoser/temperature/viewport.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

templates/thermoser/temperature/viewtemperature.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>