src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("thermoseer.urls", namespace="thermoseer")),
    path("api/", include("demo.urls")),
    path('admin/', admin.site.urls),
]

thermoseer/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = 'thermoseer'
urlpatterns = [
    path('', views.home, name="home"),
    path('login', views.loginuser, name="loginuser"),
    path('logout', views.logoutuser, name="logoutuser"),
    path('signup', views.signupuser, name="signupuser"),
    path('create/scanner', views.addId, name="add_id"),
    path('create/temperature', views.create_temperature, name="create_temperature"),
    path("thermoser/users", views.users_list, name="users_list"),
    path('thermoser/list', views.temperature_list, name='temperature_list'),
    path('thermoser/details', views.temperature_users_details, name='temperature_users_details'),
    path("thermoser/users/<int:temp_pk>", views.user_scanner_detail, name="user_scanner_detail"),
    path("thermoser/details/<int:temp_pk>", views.temperature_detail, name="temperature_detail"),

]

templates/thermoser/banner.html
{% load static %}
{% block content %}
    <div class="card" id="contentdisplay">
        <div class="banner">
            <svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="256"
                 height="256" viewBox="0 0 256 256" xml:space="preserve">

<dev>
</dev>
                <g style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; fill-rule: nonzero; opacity: 1;"
                   transform="translate(1.4065934065934016 1.4065934065934016) scale(2.81 2.81)">
	<path d="M 45 40.05 c -9.34 0 -16.939 -7.599 -16.939 -16.939 v -6.171 C 28.061 7.599 35.66 0 45 0 c 9.341 0 16.939 7.599 16.939 16.939 v 6.171 C 61.939 32.451 54.341 40.05 45 40.05 z"
          style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(55,188,140); fill-rule: nonzero; opacity: 1;"
          transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round"></path>
                    <path d="M 69.139 90 H 20.862 c -4.143 0 -7.513 -3.37 -7.513 -7.513 V 67.927 c 0 -11.157 5.701 -21.278 15.25 -27.074 c 0.745 -0.451 1.694 -0.37 2.35 0.2 c 3.91 3.398 8.9 5.27 14.052 5.27 c 5.151 0 10.142 -1.872 14.053 -5.27 c 0.657 -0.57 1.606 -0.65 2.35 -0.2 C 70.95 46.648 76.65 56.77 76.65 67.927 v 14.561 C 76.65 86.63 73.28 90 69.139 90 z"
                          style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(55,188,140); fill-rule: nonzero; opacity: 1;"
                          transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round"></path>
</g>
</svg>
        </div>
        <div class="menu">
        </div>
        <h2 class="name">detail.scanner.name</h2>
        <div class="title">{{ first_record.dept }}</div>
        <div class="actions">
            <div class="follow-info">
                <h2 style="font-size: 25px;"><a href="#"><span>{{ first_record.publish.time }}</span><small>Time</small></a></h2>
                <h2 style="font-size: 21px;"><a href="#"><span>{{ first_record.scanner_id }}</span><small id="scanner">Student ID</small></a></h2>
            </div>
            <div class="follow-btn">
                <h1 style="text-align: center; font-weight: 900; font-size: 20px;">TEMPERATURE</h1>
                <p>{{ first_record.temp }}</p>
            </div>
        </div>
    </div>
{% endblock %}


{% block domready %}
    vueApp = new Vue({
        el: "#contentdisplay",
        delimiters: ["[[", "]]"],
        data() {
            return {
                detail: {},
            };
        },

    methods: {
        currentDate() {
        const current = new Date();
        return `${current.getHours()}:${current.getMinutes() + 1}:${current.getSeconds()}`;
    }
  }
    });

    const ws = new WebSocket("ws://localhost:8000/view/data/")
    ws.onopen = function () {
        ws.send(JSON.stringify({
            action: "retrieve",
            request_id: new Date().getTime(),
        }))
    }
    ws.onmessage = function (e) {
        const allData = JSON.parse(e.data);
{#         $("#contentdisplay").css("display","none");#}
        if (allData.action === "retrieve") {
            vueApp.$data.detail = allData.data;
            vueApp.$forceUpdate();
        }else if (allData.action === "create") {
            vueApp.$data.detail = allData.data;
            vueApp.$forceUpdate();

{#            setTimeout(function() {#}
{#                    vueApp.$forceUpdate();#}
{#                    $("#contentdisplay").css("display","none");#}
{#                },#}
{#                3000);#}
{#            $("#contentdisplay").css("display","block");#}



        }
    }



{% endblock %}

templates/thermoser/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width" />
{#    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">#}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="icon" type="image/png"  href="{% static 'image/logo.png' %}">
    <link rel="stylesheet" href="{% static 'css/cards.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/weather.css' %}">
{#    <link rel="stylesheet" href="{% static 'css/base.css' %}">#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    {#    <script type="text/javascript" src="{% static 'js/display.js' %}"></script>#}
    <title>THERMOSEER</title>
</head>
<body>


<nav class="navbar navbar-expand-md navbar-light bg-warning">
<div class="container">
    <a class="navbar-brand" href="{% url 'thermoseer:home' %}">
         <img src="{% static 'image/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span>THERMOSEER</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">

                <li class="nav-item {{ current }}">
                    <a class="nav-link" href="{% url 'thermoseer:temperature_list' %}">List Temperatures</a>
                </li>
                <li class="nav-item {{ completed }}">
                    <a class="nav-link" href="{% url 'thermoseer:temperature_users_details' %}">Users Record</a>
                </li>

                 <li class="nav-item {{ create }}">
                    <a class="nav-link" href="{% url 'thermoseer:add_id' %}">Add ID</a>
                </li>

        </ul>
    {% endif %}
    <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
                    <form style='display: none;' method="POST" action="{% url 'thermoseer:logoutuser' %}">
                        {% csrf_token %}
                        <button id="signOutBtn" type="submit">Logout</button>
                    </form>
                </li>
                {% else %}
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'thermoseer:loginuser' %}">Login</a>
                </li>
                {% endif %}

                {% if user.is_authenticated and user.is_superuser %}
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'thermoseer:signupuser' %}">Sign Up</a>
                </li>

                {% endif %}
        </ul>
    </div>
</div>
</nav>

<div class="container">
{% block content %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
{#<script src="{% static 'js/display.js' %}"></script>#}
 <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14"></script>
  <script>
    $(document).ready(function() {
      {% block domready %}
      {% endblock %}
    });
  </script>

{#<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>#}
{#<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>#}
{#<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>#}
</body>

templates/thermoser/home.html
{% extends 'thermoser/base.html' %}
{% load static %}
{% block title %}Home {% endblock %}
{% block  content %}
    <div id="image-back">
        <img src="{% static 'image/uc_logo_green.png' %}" alt="uc">
    </div>
    <div>
    {% include 'thermoser/weather.html' %}
    </div>
    <div class="card" id="contentdisplay">
        <div class="banner">
            <svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="256"
                 height="256" viewBox="0 0 256 256" xml:space="preserve">

<dev>
</dev>
                <g style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; fill-rule: nonzero; opacity: 1;"
                   transform="translate(1.4065934065934016 1.4065934065934016) scale(2.81 2.81)">
	<path d="M 45 40.05 c -9.34 0 -16.939 -7.599 -16.939 -16.939 v -6.171 C 28.061 7.599 35.66 0 45 0 c 9.341 0 16.939 7.599 16.939 16.939 v 6.171 C 61.939 32.451 54.341 40.05 45 40.05 z"
          style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(55,188,140); fill-rule: nonzero; opacity: 1;"
          transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round"></path>
                    <path d="M 69.139 90 H 20.862 c -4.143 0 -7.513 -3.37 -7.513 -7.513 V 67.927 c 0 -11.157 5.701 -21.278 15.25 -27.074 c 0.745 -0.451 1.694 -0.37 2.35 0.2 c 3.91 3.398 8.9 5.27 14.052 5.27 c 5.151 0 10.142 -1.872 14.053 -5.27 c 0.657 -0.57 1.606 -0.65 2.35 -0.2 C 70.95 46.648 76.65 56.77 76.65 67.927 v 14.561 C 76.65 86.63 73.28 90 69.139 90 z"
                          style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(55,188,140); fill-rule: nonzero; opacity: 1;"
                          transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round"></path>
</g>
</svg>
        </div>
        <div class="menu">
        </div>
        <h2 class="name" style="color: #333333;">[[detail.scanner.name]]</h2>
        <div class="title" style="font-size: 20px; color: #333333;">[[detail.scanner.dept]]</div>
        <div class="actions">
            <div class="follow-info">
                <h2 style="font-size: 25px;"><a href="#"><span>[[currentDate()]]</span><small>Time</small></a>
                </h2>
                <h2 style="font-size: 21px;"><a href="#"><span>[[detail.scanner.scanner_id]]</span><small id="scanner">Student
                    ID</small></a></h2>
            </div>
            <div class="follow-btn">
                <h1 style="text-align: center; font-weight: 900; font-size: 20px; color: #333333;">TEMPERATURE</h1>
                <p>[[detail.temp]]</p>
                 <h1 id="statusTemperature" style="text-align: center; font-weight: 900; font-size: 20px; color: #ec6c0b; padding: 5px 5px;">[[detail.status]] TEMPERATURE</h1>
            </div>

        </div>
    </div>
{% endblock %}

{% block domready %}
    vueApp = new Vue({
        el: "#contentdisplay",
        delimiters: ["[[", "]]"],
        data() {
            return {
                detail: {},
            };
        },

    methods: {
        currentDate() {
        const current = new Date();
        return `${current.getHours()}:${current.getMinutes() + 1}:${current.getSeconds()}`;
    }
  }
    });

    const ws = new WebSocket("ws://localhost:8000/view/data/")
    ws.onopen = function () {
        ws.send(JSON.stringify({
            action: "retrieve",
            request_id: new Date().getTime(),
        }))
    }
    ws.onmessage = function (e) {
        const allData = JSON.parse(e.data);
{#         $("#contentdisplay").css("display","none");#}
        if (allData.action === "retrieve") {
            vueApp.$data.detail = allData.data;
            vueApp.$forceUpdate();
        }else if (allData.action === "create") {
            vueApp.$data.detail = allData.data;
            setTimeout(function() {
                    vueApp.$forceUpdate();
                    $("#contentdisplay").css("display","none");
                },
                3000);
            $("#contentdisplay").css("display","block");
            $("#statusTemperature").fadeIn()
        }
    };

 errorApp = new Vue({
        el: "#showerror",
        delimiters: ["[[", "]]"],
        data() {
            return {
                detail: {},
            };
        },

    methods: {
        currentDate() {
        const current = new Date();
        return `${current.getHours()}:${current.getMinutes() + 1}:${current.getSeconds()}`;
    }
  }
});
const error = new WebSocket("ws://localhost:8000/message/error/");
error.onopen = function () {
        error.send(JSON.stringify({
            action: "retrieve",
            request_id: new Date().getTime(),
        }))
    };

     error.onmessage = function (e) {
        const allData = JSON.parse(e.data);
        if (allData.action === "retrieve") {
            $("#showerror").css("display","none");
            errorApp.$data.detail = allData.data;
            errorApp.$forceUpdate();
        }else if (allData.action === "create") {
            errorApp.$data.detail = allData.data;
            errorApp.$forceUpdate();
            setTimeout(function() {
                    errorApp.$forceUpdate();
                    $("#showerror").css("display","none");
                },
                3000);
            $("#showerror").css("display","block");
            $("#statusTemperature").fadeIn()
        }
    };
{% endblock %}


templates/thermoser/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
    <span class="content">
        Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>

templates/thermoser/weather.html
{% load static %}
{% block content %}
<div class="container text-center">
     <div id="showerror">
         <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
        <div class="bannerHeader">
        <h1 style="color: #e8a200">[[detail.error]]</h1>
            <br/>
          <p style="font-size: 18px; font-weight: 900; color: #ec6c0b;"><strong>[[detail.description]]</strong></p>
        </div>
    </div>
  <div class="banner-weather">
    <h2 style="text-shadow:1px 1px 10px #29293d; font-size: 40px;">{{ country }}, {{ name }} Weather <img src="{{ weather_icons }}" style="opacity: 0.8;filter: alpha(opacity=80);border-radius:15px;" alt=""></h2>
      <hr class="bannerLine" />
      <h2>Timezone {{ timezone_id }}</h2>
  </div>
  <div class="main-content text-center">
    <div class="weather-data-container">
      <div class="row">
        <div class="col-xs-12 col-md-6 col-lg-6">
          <div class="clockDisplay-container">
            <p id="dateDisplay"></p>
            <h3 id="clockDisplay"></h3>
          </div>
        </div><!---end of col-xs-12-->
        <div class="col-xs-12 col-md-6 col-lg-6">
          <div class="curLocationDisp-container">
              <p style="position: relative;">
                   <small style="color: #00abff;position: absolute; left: -200%; font-size: 20px;">{{ weather_descriptions }}</small>
              </p>
            <h3 id="curLocationDisplay" style="margin: 20px;">{{ name }}</h3>
          </div>
        </div><!---end of col-xs-12-->
      </div><!---end row 1--->

      <div class="row">
        <div class="col-xs-4 col-lg-4">
          <div>
            <h4 class="disp-label">Temperature</h4>
            <p id="tempDisplay" style="color: #b24c00; font-size: 30px; font-weight: 900;">{{ temperature }}°C</p>
          </div>
        </div><!---end of col-xs-12-->
        <div class="col-xs-4 col-md-4">
          <div>
            <h4 class="disp-label">Humidity</h4>
            <p id="humidDisplay" style="color: #b24c00; font-size: 30px; font-weight: 900;">{{ humidity }}</p>
          </div>
        </div><!---end of col-xs-12-->
        <div class="col-xs-4 col-md-4">
          <div>
            <h4 class="disp-label">Wind</h4>
            <p id="windDisplay" style="color: #b24c00; font-size: 30px; font-weight: 900;">{{ wind_degree }}</p>
          </div>
        </div><!---end of col-xs-12-->

      </div><!---end row 1--->

    </div><!--end weather-data-container-->

  </div><!--end main-content-->

  </div>
</div>
{% endblock %}